class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        """
        Generate the lexicographically smallest string from str1 and str2 under
        specific constraints.

        Given two strings, str1 (length n) and str2 (length m), a string `word`
        of length n + m - 1 is defined to be generated by str1 and str2 if the
        following conditions hold for each index 0 <= i < n:

            - If str1[i] == 'T', the substring of `word` of length m starting
            at index i is equal to str2:
              word[i : i + m] == str2

            - If str1[i] == 'F', the substring of `word` of length m starting
            at index i is NOT equal to str2:
              word[i : i + m] != str2

        Returns the lexicographically smallest possible string that can be
        generated by str1 and str2.
        If no such string can be generated, returns an empty string "".

        Args:
            str1 (str): The first string of length n, representing the
            constraints with 'T' and 'F'.
            str2 (str): The second string of length m, to match or not match
            substrings in the result.

        Returns:
            str: The lexicographically smallest valid string,
            or "" if impossible.

        Example:
            Input: str1 = "TFTF", str2 = "ab"
            Output: "ababa"

        Time Complexity: O(n * m), where n = len(str1) and m = len(str2)
        Space Complexity: O(n + m)
        """
        n, m = len(str1), len(str2)
        res = [None] * (n + m - 1)
        fixed = [False] * (n + m - 1)

        for i, char in enumerate(str1):
            if char == "T":
                for j in range(m):
                    if res[i + j] is not None and res[i + j] != str2[j]:
                        return ""
                    res[i + j] = str2[j]
                    fixed[i + j] = True

        for i in range(n + m - 1):
            if res[i] is None:
                res[i] = "a"

        for i in range(n):
            if str1[i] == "F":
                match = True
                for j in range(m):
                    if res[i + j] != str2[j]:
                        match = False
                        break

                if match:
                    found_to_change = False
                    for j in range(m - 1, -1, -1):
                        if not fixed[i + j]:
                            res[i + j] = "b"
                            found_to_change = True
                            break

                    if not found_to_change:
                        return ""

        word = "".join(res)
        for i in range(n):
            if str1[i] == "T":
                if any(word[i + j] != str2[j] for j in range(m)):
                    return ""
            else:
                match = True
                for j in range(m):
                    if word[i + j] != str2[j]:
                        match = False
                        break
                if match:
                    return ""

        return word
